# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn clean test

    # Finally we upload the results to Calliope.
    - name: Upload results to Calliope
      run: curl -X POST -H "x-api-key:${{ secrets.API_KEY }}" -H "multipart/form-data" -F "file[]=@../../target/surefire-reports/testng-results.xml" "https://app.calliope.pro/api/v2/profile/${{ secrets.PROFILE_ID }}/import/testng?os=myos&platform=myplatform&build=mybuild"
